package Practice.November2022.DateNov29;

public class ExceptionHandling {
    //Exception is an unwanted or unexpected event, which occurs during the execution of a program, i.e. at run time,
    // that disrupts the normal flow of the programâ€™s instructions. Exceptions can be caught and handled by the program.
    // When an exception occurs within a method, it creates an object. This object is called the exception object.
    // It contains information about the exception,
    // such as the name and description of the exception and the state of the program when the exception occurred.
    public static void main (String[] args) {
        int a=5;
        int b=0;
       // String x = null;
       // System.out.println(x.length());
       // try{
         //   System.out.println(a/b);
      //  }
        // catch(ArithmeticException e){
        //    e.printStackTrace();
        //   }
        //  catch(ArithmeticException e){
        //      e.printStackTrace();
        //  }
     //  catch(ArithmeticException e){
       //  System.out.println(e.getMessage());}

    //    How Programmer Handles an Exception?
         //    Customized Exception Handling: Java exception handling is managed via five keywords: try, catch, throw, throws, and finally.
        //    Briefly, here is how they work. Program statements that you think can raise exceptions are contained within a try block.
        //    If an exception occurs within the try block, it is thrown. Your code can catch this exception (using catch block) and handle it in some rational manner.
        //    System-generated exceptions are automatically thrown by the Java run-time system.
        //    To manually throw an exception, use the keyword throw. Any exception that is thrown out of a method must be specified as such by a throws clause.
        //    Any code that absolutely must be executed after a try block completes is put in a finally block.

    }


}
